### ISSUE TITLE
Fatal error with php7

### ISSUE THREAD

**Issue by portal64** [ezSQL/ezSQL#109]
Hi, I've moved a project (which works fine in php5) to a shared hosting with php7, and it gives this error:

Fatal Error: ezSQL_mysql requires mySQL Lib to be compiled and or linked in to the PHP engine

Could you tell me where the problem is?

THANKS

**Comment by yohancreemers** [comment]
The class **ezSQL_mysql** uses the mysql API. This extension was deprecated in PHP 5.5.0, and it was removed in PHP 7.0.0. The MySQLi or PDO_MySQL extension should be used instead.

Easiest solution is to replace ez_sql_**mysql**.php by ez_sql_**mysqli**.php (use class **ezSQL_mysqli** instead of **ezSQL_mysql**).

**Comment by portal64** [comment]
great!  I've change it to musqli and it works perfectly now.  

THANKS for your fast answer, yohancreemers!
