### ISSUE TITLE
Question: get_var() and null values

### ISSUE THREAD

**Issue by DrewAPicture** [ezSQL/ezSQL#124]
Howdy!

I was wondering if you could share any insight your thinking behind returning `null` from `get_var()` in the case of empty values?

WordPress [forked](https://core.trac.wordpress.org/changeset/112) ezSQL many many years ago as the basis for our main `wpdb` class, and the discrepancy between empty value handling in `get_col()` (via `get_var()`) and `get_results()` has only been recently noticed.

I've filed a [ticket](https://core.trac.wordpress.org/ticket/40953) on WordPress Core Trac discussing the discrepancy, but I wondered if you had any insight on why `get_var()` was designed this way?

**Background:**

Let's say you're running a MySQL query like `SELECT rate FROM sometable` through `get_results()`. With the default parameters and empty values for the column, you'd get something like the following:
```
array(2) {
  [0]=>
  object(stdClass)#1734 (1) {
    ["rate"]=>
    string(0) ""
  }
  [1]=>
  object(stdClass)#1735 (1) {
    ["rate"]=>
    string(0) ""
  }
}
```

If you ran that same query through `get_col()`, you'd instead get an array of null values:
```
array(4) {
  [0]=>
  NULL
  [1]=>
  NULL
}
```

This seems oddly inconsistent. And writing tests for the workaround is annoying in that creates the need to understand the core workaround in the future.

**Comment by jv2222** [comment]
Hey Drew,

To my way of thinking back then null was like saying undefined in
javascript. It seemed like an empty string was "something" and null was
"nothing" and therefor it made sense to return nothing, if nothing was in
the results.

I'm not saying that's a good reason, just answering your question about
what the thinking was.

But, as you point out, that is not consistent with get_results.

So, I do think it would be sensible for you guys to make it consistent
within wpdb.

I guess the only problem would be if wp plugin creators did checks using
the === null  rather than == false.

I guess given the massive amount of code that has been written on top of
wpdb it's bound to break some stuff out there.

That said, it would still be worth the trade off IMHO.

FYI I haven't worked on mySQL for 7+ years at this point it's being
maintained by felix and the github community.

Justin

**Comment by DrewAPicture** [comment]
Hey Justin,

Thanks for the insight. I figured it was something like that. Whatever we do, the default behavior ship sailed a long time ago. We're looking at global flag options and benchmarking some scenarios to figure out what the performace impact would be. Thanks again :-)
