### ISSUE TITLE
No prepared statement usage examples in documentation

### ISSUE THREAD

**Issue by kkumar326** [ezSQL/ezSQL#142]
Prepared statements implementation is not covered in documentation. It'd be really great if some basic examples are added.

Thanks.

**Comment by techno-express** [comment]
I will need to update the docs, but to get started. 
If take a look at the **phpunit tests** for **mysqli** there is an example, they all work the same way.

**```query_prepared($query_string, $param_array)```**

It easier and automatic if you using _shortcut method calls_, the **query builder**, because it will eventfully be called. You will need to call the function  **`setPrepare(true)`** once to use. 
This library is setup to either _escape_ or use _prepare_ statements _automatically_, if using the **query builder**.  _Preventing SQL injection is at work_, if using **query builder**, escaping all parameters is the default.

The other method to still get the same protection is by if using **```query_prepared($query_string, $param_array)```**, and supplying the the whole **query string**, and placing **'?'**, with the ** same number of arguments in an array**.

**Example:
```query_prepared('INSERT INTO unit_test(id, test_key) VALUES(1, ?)', ['test 1']);```**

_**It will determine arguments type, execute, and return results.**_

**Comment by terrybr** [comment]
Using query_prepared($query, $params) returns this error:

**Call to a member function prepare() on null in \ezsql\lib\ez_sql_mysqli.php on line 312**

**Comment by techno-express** [comment]
That type of error indicates no class instance object is being used. 
You might be using the wrong variable.

**Comment by terrybr** [comment]
I can do $db->query($query); or any other query for that matter,  but $db->query_prepared($query, $params) triggers the error.

**Comment by techno-express** [comment]
What's the SQL statement string you using? And the method call expects the second argument to be an array of values. What database SQL driver are you using, mysql, postgres, sqlite3, or ms sqlserver? 

If it's a problem in this library then the phpunit tests covering this method, would be failing producing the same error.

I would need the code source example you are using to narrow down what's generating the problem/error.

**Comment by terrybr** [comment]
Here's the code:

`		
require_once 'vendors/ezsql/ez_sql_loader.php';

$db = new ezSQL_mysqli('root', '', 'stats', 'localhost');
$db->setPrepare(true);

$query_string = 'INSERT INTO games (date_start,map_name,game_type) VALUES (?,?,?)';

$q = $db->query_prepared($query_string , [
	"value1",
	"value2",
	"value3",
]);
`

**Comment by techno-express** [comment]
Since your are using composer try:
**`require 'vendor/autoload.php'`;**

Also test putting everything in an check like:
```
if ($db instanceof ezSQL_mysqli) {
    // your code
}  else
    // error you don't have an class instance

```
The phunit test for the method is in https://github.com/ezSQL/ezSQL/blob/master/tests/mysqli/ezSQL_mysqliTest.php

**Note:**
The **` $db->setPrepare(true);`** call is needed for the **`insert()`** and all shortcut method calls. 

You are providing the full SQL string. The shortcut methods produces that for you, it captures everything and the values from the arguments.

**Comment by techno-express** [comment]
Addressing in v4 release https://github.com/ezSQL/ezSQL/releases/latest
