### ISSUE TITLE
Initialize Multiple Databases

### ISSUE THREAD

**Issue by daza110** [ezSQL/ezsql#176]
Is it possible to initialize multiple databases?? I have the following code which in my mind should work, but it does not.

use ezsql\Database;

$db = Database::initialize('mysqli',['user1','user1pass','firstdb','localhost'],'');
$WebDB = Database::initialize('mysqli',['user2','user2pass','seconddb','localhost'],'');

If I then try and run:
$WebDB->get_results("SELECT * FROM wpforms_entries");

I get the following error:  Warning: Table 'firstdb.wpforms_entries' doesn't exist in /srv/vendor/ezsql/ezsql/lib/ezsqlModel.php on line 225

This should of course not be looking at the firstdb as im calling it through $WebDB not $db

**Comment by techno-express** [comment]
Yes, it is designed to work with multiple databases, but the last parameter, should be an `tag` to indicate it, otherwise it will use first instance.
`$WebDB = Database::initialize('mysqli',['user2','user2pass','seconddb','localhost'], tagsome);`
Thereafter, the object instance can always be retrieved with `tagInstance(tagsome)`

But now looking over the code, it will always return first instance, cause an oversight or just not actually testing the feature. The check in `Database.php' line 36, not checking for the $tag being passed it. 

It needs to be changed to:
`if (isset(self::$instances[$vendor]) && empty($setting) && empty($tag))`

Test with the change and submit PR.

**Comment by daza110** [comment]
I can confirm that upon editing that line and adding a unique tag multiple database initialization works fine. Thanks.

**Comment by OscarWilde** [comment]
If inititialized two Databases like this:
`$db = Database::initialize('mysqli', [DBUSER, DBPASSWORD, DBNAME], 'db1');`
`$db2 = Database::initialize('mysqli', [DB2USER, DB2PASSWORD, DB2NAME], 'db2');`

But if I try to run a Query on $db2 it is still the same Problem. 
`$db2->query('SQL STATEMENT');`

Can you do an Example, how to access the second DB? I do not really understand what you mean with: 
> Thereafter, the object instance can always be retrieved with tagInstance(tagsome)

**Comment by techno-express** [comment]
What version you using? That part of the code haven't changed since you said worked update. 

The example you just wrote should return new instance.

**Comment by OscarWilde** [comment]
Yes it worked, I had some Querys between the initialisation and that seems to produce some error. But without that, it worked. Thanks!

**Comment by techno-express** [comment]
You would need to give full example, some code that i can check out. Or create a PR of a test that would produce that error.

Otherwise, it will just be a back in forth leading nowhere with this issue.
